version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"  # Порт PHP-FPM
      - "8000:8000"  # Порт laravel dev сервера
      - "3000:3000"  # Порт Vite
      - "4173:4173"  # Порт Vite
    expose:
      - "9000"
      - "8000"
      - "3000"
      - "4173"
    environment:
      DB_CONNECTION: mysql
      DB_DATABASE: blog
      DB_USERNAME: lara_user
      DB_PASSWORD: your_user_password
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password_lara
      MYSQL_DATABASE: blog
      MYSQL_USER: lara_user
      MYSQL_PASSWORD: your_user_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network
    ports:
      - 33060:3306

  nginx:
    image: nginx:latest
    ports:
      - 8088:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www
    depends_on:
      - app
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db_data:
